#!/bin/bash
# shellcheck disable=SC2034

# This file contains a mapping of common composer last names (from filenames)
# to their full names for PDF metadata population.
# It is sourced by the main bash_metadata_script.sh.

declare -gA composer_full_names

# Comprehensive Composer List (A-C)
# Sourced from Wikipedia's List of Composers.

# A
composer_full_names["Aa"]="Michel van der Aa"
composer_full_names["Aagaard"]="Thorvald Aagaard"
composer_full_names["Aagesen"]="Truid Aagesen"
composer_full_names["Aaltoila"]="Heikki Aaltoila"
composer_full_names["Aavik"]="Juhan Aavik"
composer_full_names["dall'Abaco"]="Evaristo Felice dall'Abaco"
composer_full_names["Abaco"]="Joseph Abaco"
composer_full_names["Abbatini"]="Antonio Maria Abbatini"
composer_full_names["Abdel-Rahim"]="Gamal Abdel-Rahim"
composer_full_names["Abdelfattah"]="Mohamed Abdelwahab Abdelfattah"
composer_full_names["Abdi"]="Behzad Abdi"
composer_full_names["Abe"]="Keiko Abe"
composer_full_names["aBeckett"]="Mary Anne à Beckett"
composer_full_names["Abejo"]="Rosalina Abejo"
composer_full_names["Abel"]="Carl Friedrich Abel"
composer_full_names["Abelard"]="Peter Abelard"
composer_full_names["Abell"]="John Abell"
composer_full_names["Abendroth"]="Walter Abendroth"
composer_full_names["Abert"]="Johann Joseph Abert"
composer_full_names["Abos"]="Girolamo Abos"
composer_full_names["Abraham"]="Paul Abraham"
composer_full_names["Abrahamsen"]="Hans Abrahamsen"
composer_full_names["Abreu"]="Zequinha de Abreu"
composer_full_names["Absil"]="Jean Absil"
composer_full_names["Abt"]="Franz Abt"
composer_full_names["Accolay"]="Jean-Baptiste Accolay"
composer_full_names["Achron"]="Joseph Achron"
composer_full_names["Acker"]="Dieter Acker"
composer_full_names["Adalid"]="Marcial del Adalid"
composer_full_names["Adam"]="Adolphe Adam"
composer_full_names["Adamo"]="Mark Adamo"
composer_full_names["Adams"]="John Adams"
composer_full_names["Addinsell"]="Richard Addinsell"
composer_full_names["Addison"]="John Addison"
composer_full_names["Ades"]="Thomas Adès"
composer_full_names["Adler"]="Samuel Adler"
composer_full_names["Adlgasser"]="Anton Cajetan Adlgasser"
composer_full_names["Adolphe"]="Bruce Adolphe"
composer_full_names["Agazzari"]="Agostino Agazzari"
composer_full_names["Agnesi"]="Maria Teresa Agnesi"
composer_full_names["Agostini"]="Lodovico Agostini"
composer_full_names["Agricola"]="Alexander Agricola"
composer_full_names["Aguado"]="Dionisio Aguado"
composer_full_names["Aguilera de Heredia"]="Sebastian Aguilera de Heredia"
composer_full_names["Ahle"]="Johann Rudolph Ahle"
composer_full_names["Aho"]="Kalevi Aho"
composer_full_names["Alain"]="Jehan Alain"
composer_full_names["Albeniz"]="Isaac Albéniz"
composer_full_names["d'Albert"]="Eugen d'Albert"
composer_full_names["Alberti"]="Domenico Alberti"
composer_full_names["Albinoni"]="Tomaso Albinoni"
composer_full_names["Albrechtsberger"]="Johann Georg Albrechtsberger"
composer_full_names["Alfven"]="Hugo Alfvén"
composer_full_names["Alkan"]="Charles-Valentin Alkan"
composer_full_names["Allegri"]="Gregorio Allegri"
composer_full_names["Allende"]="Pedro Humberto Allende"
composer_full_names["Alwyn"]="William Alwyn"
composer_full_names["Ammerbach"]="Elias Nikolaus Ammerbach"
composer_full_names["Amon"]="Johann Andreas Amon"
composer_full_names["Anderson"]="Leroy Anderson"
composer_full_names["Andree"]="Elfrida Andrée"
composer_full_names["Andre"]="Johann André"
composer_full_names["Andriessen"]="Hendrik Andriessen"
composer_full_names["Anerio"]="Felice Anerio"
composer_full_names["d'Anglebert"]="Jean-Henri d'Anglebert"
composer_full_names["Ansorge"]="Conrad Ansorge"
composer_full_names["Antheil"]="George Antheil"
composer_full_names["Araja"]="Francesco Araja"
composer_full_names["Arcadelt"]="Jacques Arcadelt"
composer_full_names["Arensky"]="Anton Arensky"
composer_full_names["Ariosti"]="Attilio Ariosti"
composer_full_names["Arne"]="Thomas Arne"
composer_full_names["Arnold"]="Malcolm Arnold"
composer_full_names["Arriaga"]="Juan Crisóstomo de Arriaga"
composer_full_names["Artusi"]="Giovanni Artusi"
composer_full_names["Asafyev"]="Boris Asafyev"
composer_full_names["d'Astorga"]="Emanuele d'Astorga"
composer_full_names["Attaingnant"]="Pierre Attaingnant"
composer_full_names["Atterberg"]="Kurt Atterberg"
composer_full_names["Attwood"]="Thomas Attwood"
composer_full_names["Auber"]="Daniel Auber"
composer_full_names["Aubert"]="Louis Aubert"
composer_full_names["Aulin"]="Tor Aulin"
composer_full_names["Auric"]="Georges Auric"
composer_full_names["Avison"]="Charles Avison"

# B
composer_full_names["Babbitt"]="Milton Babbitt"
composer_full_names["Bacarisse"]="Salvador Bacarisse"
composer_full_names["Bacewicz"]="Grażyna Bacewicz"
composer_full_names["CPEBach"]="Carl Philipp Emanuel Bach"
composer_full_names["JCBach"]="Johann Christian Bach"
composer_full_names["JSBach"]="Johann Sebastian Bach"
composer_full_names["WFBach"]="Wilhelm Friedemann Bach"
composer_full_names["Bacon"]="Ernst Bacon"
composer_full_names["Badings"]="Henk Badings"
composer_full_names["Bainton"]="Edgar Bainton"
composer_full_names["Baird"]="Tadeusz Baird"
composer_full_names["Balakirev"]="Mily Balakirev"
composer_full_names["Balbastre"]="Claude Balbastre"
composer_full_names["Bantock"]="Granville Bantock"
composer_full_names["Barber"]="Samuel Barber"
composer_full_names["Bargiel"]="Woldemar Bargiel"
composer_full_names["Barnby"]="Joseph Barnby"
composer_full_names["Barraque"]="Jean Barraqué"
composer_full_names["Barrios"]="Agustín Barrios"
composer_full_names["Bartok"]="Béla Bartók"
composer_full_names["Bassani"]="Giovanni Battista Bassani"
composer_full_names["Bax"]="Arnold Bax"
composer_full_names["Bazzini"]="Antonio Bazzini"
composer_full_names["Beach"]="Amy Beach"
composer_full_names["Beethoven"]="Ludwig van Beethoven"
composer_full_names["Bellini"]="Vincenzo Bellini"
composer_full_names["Benda"]="Georg Benda"
composer_full_names["Benjamin"]="Arthur Benjamin"
composer_full_names["Bennett"]="William Sterndale Bennett"
composer_full_names["Benoit"]="Peter Benoit"
composer_full_names["Bentzon"]="Niels Viggo Bentzon"
composer_full_names["Berg"]="Alban Berg"
composer_full_names["Berger"]="Wilhelm Berger"
composer_full_names["Berio"]="Luciano Berio"
composer_full_names["deBeriot"]="Charles Auguste de Bériot"
composer_full_names["Berkeley"]="Lennox Berkeley"
composer_full_names["Berlioz"]="Hector Berlioz"
composer_full_names["Bernstein"]="Leonard Bernstein"
composer_full_names["Berwald"]="Franz Berwald"
composer_full_names["Biber"]="Heinrich Ignaz Franz von Biber"
composer_full_names["Billings"]="William Billings"
composer_full_names["Binchois"]="Gilles Binchois"
composer_full_names["Bizet"]="Georges Bizet"
composer_full_names["Bliss"]="Arthur Bliss"
composer_full_names["Blitzstein"]="Marc Blitzstein"
composer_full_names["Bloch"]="Ernest Bloch"
composer_full_names["Blow"]="John Blow"
composer_full_names["Boccherini"]="Luigi Boccherini"
composer_full_names["Boellmann"]="Léon Boëllmann"
composer_full_names["Boely"]="Alexandre Pierre François Boëly"
composer_full_names["Boismortier"]="Joseph Bodin de Boismortier"
composer_full_names["Boito"]="Arrigo Boito"
composer_full_names["Bolcom"]="William Bolcom"
composer_full_names["Boonzaaier"]="Kristi Boonzaaier"
composer_full_names["Bondeville"]="Emmanuel Bondeville"
composer_full_names["Bonporti"]="Francesco Antonio Bonporti"
composer_full_names["Borodin"]="Alexander Borodin"
composer_full_names["Bortniansky"]="Dmitry Bortniansky"
composer_full_names["Bossi"]="Marco Enrico Bossi"
composer_full_names["Bottesini"]="Giovanni Bottesini"
composer_full_names["Boughton"]="Rutland Boughton"
composer_full_names["BoulangerL"]="Lili Boulanger"
composer_full_names["BoulangerN"]="Nadia Boulanger"
composer_full_names["Boulez"]="Pierre Boulez"
composer_full_names["Boyce"]="William Boyce"
composer_full_names["Brahms"]="Johannes Brahms"
composer_full_names["Brian"]="Havergal Brian"
composer_full_names["Bridge"]="Frank Bridge"
composer_full_names["Britten"]="Benjamin Britten"
composer_full_names["Bruch"]="Max Bruch"
composer_full_names["Bruckner"]="Anton Bruckner"
composer_full_names["Bruneau"]="Alfred Bruneau"
composer_full_names["Bull"]="John Bull"
composer_full_names["Burgmuller"]="Norbert Burgmüller"
composer_full_names["Busnois"]="Antoine Busnois"
composer_full_names["Busoni"]="Ferruccio Busoni"
composer_full_names["Buxtehude"]="Dieterich Buxtehude"
composer_full_names["Byrd"]="William Byrd"

# C
composer_full_names["Cabezon"]="Antonio de Cabezón"
composer_full_names["Caccini"]="Giulio Caccini"
composer_full_names["Cage"]="John Cage"
composer_full_names["Caldara"]="Antonio Caldara"
composer_full_names["Campra"]="André Campra"
composer_full_names["Cannabich"]="Christian Cannabich"
composer_full_names["Caplet"]="André Caplet"
composer_full_names["Carissimi"]="Giacomo Carissimi"
composer_full_names["Carter"]="Elliott Carter"
composer_full_names["Carulli"]="Ferdinando Carulli"
composer_full_names["Carvalho"]="João de Sousa Carvalho"
composer_full_names["Casella"]="Alfredo Casella"
composer_full_names["Castelnuovo-Tedesco"]="Mario Castelnuovo-Tedesco"
composer_full_names["Catalani"]="Alfredo Catalani"
composer_full_names["Cavalli"]="Francesco Cavalli"
composer_full_names["Cavalieri"]="Emilio de' Cavalieri"
composer_full_names["Cervantes"]="Ignacio Cervantes"
composer_full_names["Chabrier"]="Emmanuel Chabrier"
composer_full_names["Chadwick"]="George Whitefield Chadwick"
composer_full_names["Chaminade"]="Cécile Chaminade"
composer_full_names["Charpentier"]="Marc-Antoine Charpentier"
composer_full_names["Chausson"]="Ernest Chausson"
composer_full_names["Chavez"]="Carlos Chávez"
composer_full_names["Cherubini"]="Luigi Cherubini"
composer_full_names["Chopin"]="Frédéric Chopin"
composer_full_names["Ciconia"]="Johannes Ciconia"
composer_full_names["Cilea"]="Francesco Cilea"
composer_full_names["Cimarosa"]="Domenico Cimarosa"
composer_full_names["Clarke"]="Rebecca Clarke"
composer_full_names["Clementi"]="Muzio Clementi"
composer_full_names["Coleridge-Taylor"]="Samuel Coleridge-Taylor"
composer_full_names["Copland"]="Aaron Copland"
composer_full_names["Corelli"]="Arcangelo Corelli"
composer_full_names["Cornelius"]="Peter Cornelius"
composer_full_names["Corrette"]="Michel Corrette"
composer_full_names["Couperin"]="François Couperin"
composer_full_names["Cowen"]="Frederic Hymen Cowen"
composer_full_names["Cramer"]="Johann Baptist Cramer"
composer_full_names["Cras"]="Jean Cras"
composer_full_names["Crecquillon"]="Thomas Crecquillon"
composer_full_names["Crumb"]="George Crumb"
composer_full_names["Crusell"]="Bernhard Crusell"
composer_full_names["Cui"]="César Cui"
composer_full_names["Czerny"]="Carl Czerny"

# D
composer_full_names["Debussy"]="Claude Debussy"
composer_full_names["Delibes"]="Léo Delibes"
composer_full_names["Delius"]="Frederick Delius"
composer_full_names["Donizetti"]="Gaetano Donizetti"
composer_full_names["Dowland"]="John Dowland"
composer_full_names["Dukas"]="Paul Dukas"
composer_full_names["Dvorak"]="Antonín Dvořák"

# E
composer_full_names["Elgar"]="Edward Elgar"
composer_full_names["Enescu"]="George Enescu"

# F
composer_full_names["Falla"]="Manuel de Falla"
composer_full_names["Faure"]="Gabriel Fauré"
composer_full_names["Feldman"]="Morton Feldman"
composer_full_names["Franck"]="César Franck"
composer_full_names["Frescobaldi"]="Girolamo Frescobaldi"

# G
composer_full_names["Gabrieli"]="Giovanni Gabrieli"
composer_full_names["Gershwin"]="George Gershwin"
composer_full_names["Gesualdo"]="Carlo Gesualdo"
composer_full_names["Gibbons"]="Orlando Gibbons"
composer_full_names["Ginastera"]="Alberto Ginastera"
composer_full_names["Glass"]="Philip Glass"
composer_full_names["Glazunov"]="Alexander Glazunov"
composer_full_names["Glinka"]="Mikhail Glinka"
composer_full_names["Gluck"]="Christoph Willibald Gluck"
composer_full_names["Gounod"]="Charles Gounod"
composer_full_names["Grieg"]="Edvard Grieg"

# H
composer_full_names["Handel"]="George Frideric Handel"
composer_full_names["Haydn"]="Joseph Haydn"
composer_full_names["Henze"]="Hans Werner Henze"
composer_full_names["Hildegard"]="Hildegard von Bingen"
composer_full_names["Hindemith"]="Paul Hindemith"
composer_full_names["Holst"]="Gustav Holst"
composer_full_names["Honegger"]="Arthur Honegger"
composer_full_names["Hummel"]="Johann Nepomuk Hummel"

# I
composer_full_names["Ives"]="Charles Ives"

# J
composer_full_names["Janacek"]="Leoš Janáček"
composer_full_names["Joplin"]="Scott Joplin"
composer_full_names["Josquin"]="Josquin des Prez"

# K
composer_full_names["Khachaturian"]="Aram Khachaturian"
composer_full_names["Kodaly"]="Zoltán Kodály"
composer_full_names["Kreisler"]="Fritz Kreisler"
composer_full_names["Kreutzer"]="Rodolphe Kreutzer"

# L
composer_full_names["Lalo"]="Édouard Lalo"
composer_full_names["Lassus"]="Orlande de Lassus"
composer_full_names["Lehar"]="Franz Lehár"
composer_full_names["Ligeti"]="György Ligeti"
composer_full_names["Liszt"]="Franz Liszt"
composer_full_names["Lully"]="Jean-Baptiste Lully"
composer_full_names["Lutoslawski"]="Witold Lutosławski"

# M
composer_full_names["Machaut"]="Guillaume de Machaut"
composer_full_names["Mahler"]="Gustav Mahler"
composer_full_names["Mascagni"]="Pietro Mascagni"
composer_full_names["Massenet"]="Jules Massenet"
composer_full_names["Mendelssohn"]="Felix Mendelssohn"
composer_full_names["Messiaen"]="Olivier Messiaen"
composer_full_names["Meyerbeer"]="Giacomo Meyerbeer"
composer_full_names["Milhaud"]="Darius Milhaud"
composer_full_names["Monteverdi"]="Claudio Monteverdi"
composer_full_names["Mozart"]="Wolfgang Amadeus Mozart"
composer_full_names["Mussorgsky"]="Modest Mussorgsky"

# N
composer_full_names["Nielsen"]="Carl Nielsen"

# O
composer_full_names["Offenbach"]="Jacques Offenbach"
composer_full_names["Orff"]="Carl Orff"

# P
composer_full_names["Pachelbel"]="Johann Pachelbel"
composer_full_names["Paganini"]="Niccolò Paganini"
composer_full_names["Palestrina"]="Giovanni Pierluigi da Palestrina"
composer_full_names["Part"]="Arvo Pärt"
composer_full_names["Pergolesi"]="Giovanni Battista Pergolesi"
composer_full_names["Poulenc"]="Francis Poulenc"
composer_full_names["Prokofiev"]="Sergei Prokofiev"
composer_full_names["Puccini"]="Giacomo Puccini"
composer_full_names["Purcell"]="Henry Purcell"

# R
composer_full_names["Rachmaninoff"]="Sergei Rachmaninoff"
composer_full_names["Rameau"]="Jean-Philippe Rameau"
composer_full_names["Ravel"]="Maurice Ravel"
composer_full_names["Reger"]="Max Reger"
composer_full_names["Reicha"]="Anton Reicha"
composer_full_names["Respighi"]="Ottorino Respighi"
composer_full_names["RimskyKorsakov"]="Nikolai Rimsky-Korsakov"
composer_full_names["Rodrigo"]="Joaquín Rodrigo"
composer_full_names["Ropartz"]="Joseph Guy Ropartz"
composer_full_names["Rossini"]="Gioachino Rossini"

# S
composer_full_names["Saint-Saens"]="Camille Saint-Saëns"
composer_full_names["Sarasate"]="Pablo de Sarasate"
composer_full_names["Satie"]="Erik Satie"
composer_full_names["ScarlattiA"]="Alessandro Scarlatti"
composer_full_names["ScarlattiD"]="Domenico Scarlatti"
composer_full_names["Schoenberg"]="Arnold Schoenberg"
composer_full_names["Schubert"]="Franz Schubert"
composer_full_names["Schumann"]="Robert Schumann"
composer_full_names["Schutz"]="Heinrich Schütz"
composer_full_names["Scriabin"]="Alexander Scriabin"
composer_full_names["Shostakovich"]="Dmitri Shostakovich"
composer_full_names["Sibelius"]="Jean Sibelius"
composer_full_names["Smetana"]="Bedřich Smetana"
composer_full_names["Sousa"]="John Philip Sousa"
composer_full_names["StraussJ"]="Johann Strauss II"
composer_full_names["StraussII"]="Johann Strauss II"
composer_full_names["Strauss"]="Johann Strauss II"
composer_full_names["StraussR"]="Richard Strauss"
composer_full_names["Stravinsky"]="Igor Stravinsky"
composer_full_names["Suppe"]="Franz von Suppé"
composer_full_names["Sweelinck"]="Jan Pieterszoon Sweelinck"
composer_full_names["Szymanowski"]="Karol Szymanowski"

# T
composer_full_names["Tallis"]="Thomas Tallis"
composer_full_names["Tchaikovsky"]="Pyotr Ilyich Tchaikovsky"
composer_full_names["Telemann"]="Georg Philipp Telemann"
composer_full_names["Thomas"]="Ambroise Thomas"
composer_full_names["Tomasi"]="Henri Tomasi"
composer_full_names["Turina"]="Joaquín Turina"

# U
composer_full_names["Uccellini"]="Marco Uccellini"

# V
composer_full_names["Varese"]="Edgard Varèse"
composer_full_names["VaughanWilliams"]="Ralph Vaughan Williams"
composer_full_names["Verdi"]="Giuseppe Verdi"
composer_full_names["Victoria"]="Tomás Luis de Victoria"
composer_full_names["Villa-Lobos"]="Heitor Villa-Lobos"
composer_full_names["Vivaldi"]="Antonio Vivaldi"
composer_full_names["Viadana"]="Lodovico Viadana"
composer_full_names["Vierne"]="Louis Vierne"

# W
composer_full_names["Wagner"]="Richard Wagner"
composer_full_names["Walton"]="William Walton"
composer_full_names["Weber"]="Carl Maria von Weber"
composer_full_names["Webern"]="Anton Webern"
composer_full_names["Widor"]="Charles-Marie Widor"
composer_full_names["Wolf"]="Hugo Wolf"
