version: "3"

vars:
  PYTHON_VERSION: '{{.PYTHON_VERSION | default "3.13"}}'

tasks:
  default:
    desc: "Install development dependencies and run all tests for the project."
    cmds:
      - task: install-dev
      - task: test

  install:
    desc: "Install the project with production dependencies."
    cmds:
      - . .venv/bin/activate && uv pip install -e .
    status:
      - test -d .venv

  install-dev:
    desc: "Install the project with development dependencies."
    cmds:
      - python{{.PYTHON_VERSION}} -m venv .venv
      - . .venv/bin/activate && uv pip install -e '.[dev]'
    status:
      - test -d .venv

  run:
    desc: "Run the sheetmusic-metadata CLI tool."
    cmds:
      - . .venv/bin/activate && sheetmusic-metadata

  test:
    desc: "Run the pytest test suite."
    cmds:
      - . .venv/bin/activate && pytest

  clean:
    desc: "Remove temporary files and the virtual environment."
    cmds:
      - rm -rf .venv
      - rm -rf .pytest_cache
      - rm -rf .ruff_cache
      - find . -type f -name '*.pyc' -delete
      - find . -type d -name '__pycache__' -delete
