version: '3'

tasks:
  default:
    desc: "Run all linting and tests for the project."
    cmds:
      - task: lint
      - task: test

  install:
    desc: "Install the package for usage (production dependencies only)."
    deps:
      - check-deps
    cmds:
      - uv sync
    status:
      # Check if virtual environment exists
      - test -d .venv

  install-dev:
    desc: "Install the package in development mode with all dev dependencies and pre-commit hooks."
    deps:
      - check-deps
    cmds:
      - uv sync --extra dev --extra lint --extra test
      - uv run pre-commit install
    status:
      # Check if virtual environment exists
      - test -d .venv

  check-deps:
    desc: "Check for and install missing tools (Python 3.13, uv, exiftool)."
    cmds:
      - |
        if ! command -v brew &> /dev/null; then
          echo "Error: Homebrew is not installed. Please install Homebrew, or install dependencies manually." >&2
          exit 1
        fi
        echo "Info: Installing dependencies with Homebrew..."
        brew install exiftool
        if ! command -v uv &> /dev/null; then
          echo "Info: Installing uv..."
          curl -LsSf https://astral.sh/uv/install.sh | sh
        fi
    status:
      - command -v python3.13 >/dev/null 2>&1
      - command -v uv >/dev/null 2>&1
      - command -v exiftool >/dev/null 2>&1
    silent: true

  lint:
    desc: "Run Python linters (ruff)."
    deps:
      - install-dev
    cmds:
      - uv run ruff check sheetmusic_metadata tests
      - uv run ruff format --check sheetmusic_metadata tests

  test:
    desc: "Run the pytest test suite in parallel."
    deps:
      - install-dev
    cmds:
      - uv run pytest tests/ -v -n auto

  test-integration:
    desc: "Run only integration tests in parallel (requires exiftool)."
    deps:
      - install-dev
    cmds:
      - uv run pytest tests/test_pdf_integration.py -v -n auto

  test-unit:
    desc: "Run only unit tests in parallel (no exiftool required)."
    deps:
      - install-dev
    cmds:
      - uv run pytest tests/ -v -k "not integration" -n auto

  test-serial:
    desc: "Run tests serially (useful for debugging)."
    deps:
      - install-dev
    cmds:
      - uv run pytest tests/ -v

  clean:
    desc: "Remove virtual environment, cache files, and temporary files."
    cmds:
      - |
        echo "Cleaning virtual environment..."
        rm -rf .venv
      - |
        echo "Cleaning Python cache files..."
        find . -type d -name "__pycache__" -not -path "./.git/*" -exec rm -r {} + 2>/dev/null || true
        find . -type f -name "*.pyc" -not -path "./.git/*" -delete 2>/dev/null || true
        find . -type f -name "*.pyo" -not -path "./.git/*" -delete 2>/dev/null || true
      - |
        echo "Cleaning test and lint cache files..."
        rm -rf .pytest_cache
        rm -rf .ruff_cache
        rm -rf .coverage
        rm -rf htmlcov
        rm -rf .mypy_cache
        rm -rf .tox
      - |
        echo "Cleaning build artifacts..."
        rm -rf dist
        rm -rf build
        find . -type d -name "*.egg-info" -not -path "./.git/*" -exec rm -r {} + 2>/dev/null || true
      - |
        echo "Cleaning temporary files..."
        find . -type f -name "*.tmp" -not -path "./.git/*" -not -path "./tests/support/*" -delete 2>/dev/null || true
        find . -type f -name "*.bak" -not -path "./.git/*" -not -path "./tests/support/*" -delete 2>/dev/null || true
        find . -type f -name "*~" -not -path "./.git/*" -not -path "./tests/support/*" -delete 2>/dev/null || true
      - echo "Clean complete!"

  run:
    desc: "Run the CLI tool (usage: task run -- [args] or task run)."
    deps:
      - install
    cmds:
      - uv run sheetmusic-metadata {{if .CLI_ARGS}}{{.CLI_ARGS}}{{end}}
