version: '3'

tasks:
  default:
    desc: "Run all linting and tests for the project."
    cmds:
      - task: lint
      - task: test

  setup:
    desc: "Set up the development environment by installing dependencies with uv."
    deps:
      - check-deps
    cmds:
      - uv sync --extra dev
    status:
      # Check if virtual environment exists
      - test -d .venv

  check-deps:
    desc: "Check for and install missing tools (Python 3.13, uv, exiftool)."
    cmds:
      - |
        if ! command -v brew &> /dev/null; then
          echo "Error: Homebrew is not installed. Please install Homebrew, or install dependencies manually." >&2
          exit 1
        fi
        echo "Info: Installing dependencies with Homebrew..."
        brew install exiftool
        if ! command -v uv &> /dev/null; then
          echo "Info: Installing uv..."
          curl -LsSf https://astral.sh/uv/install.sh | sh
        fi
    status:
      - command -v python3.13 >/dev/null 2>&1
      - command -v uv >/dev/null 2>&1
      - command -v exiftool >/dev/null 2>&1
    silent: true

  lint:
    desc: "Run Python linters (ruff if available)."
    deps:
      - setup
    cmds:
      - |
        if uv run python -c "import ruff" 2>/dev/null; then
          uv run ruff check sheetmusic_metadata tests
          uv run ruff format --check sheetmusic_metadata tests
        else
          echo "Note: ruff not installed. Skipping linting. Install with: uv add --dev ruff"
        fi

  test:
    desc: "Run the pytest test suite."
    deps:
      - setup
    cmds:
      - uv run pytest tests/ -v

  test-integration:
    desc: "Run only integration tests (requires exiftool)."
    deps:
      - setup
    cmds:
      - uv run pytest tests/test_pdf_integration.py -v

  test-unit:
    desc: "Run only unit tests (no exiftool required)."
    deps:
      - setup
    cmds:
      - uv run pytest tests/ -v -k "not integration"

  install:
    desc: "Install the package in development mode."
    deps:
      - setup
    cmds:
      - uv pip install -e .

  run:
    desc: "Run the CLI tool (usage: task run -- [args] or task run)."
    deps:
      - setup
    cmds:
      - uv run sheetmusic-metadata {{if .CLI_ARGS}}{{.CLI_ARGS}}{{end}}
